# Numpy
- Numpy is a general purpose array processing package
- NumPy is a Python library used for working with arrays.
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
- NumPy stands for Numerical Python.
- It provides a high performance multidimensional array object and tools for working with these array
- It is a fundamental package for scientific computing with python

# Why Use NumPy?
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.

# What is an array
- An array is a data structure that stores values for same datatype. In python this the main difference between arrays and lists
- While python list can contain values corresponding to different datatype,array in python can only contain values corresponding to the same datatype. 

In [6]:
# Installation of NumPy
# pip install numpy

In [7]:
# Import NumPy
import numpy

In [8]:
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## NumPy as np
- NumPy is usually imported under the np alias.
- alias: In Python alias are an alternate name for referring to the same thing.

In [9]:
import numpy as np

In [11]:
my_list=[1,2,3,4,4]
arra=np.array(my_list)
print(arra)

[1 2 3 4 4]


In [12]:
type(arra)

numpy.ndarray

## Shape of an Array
The shape of an array is the number of elements in each dimension.
It specify how many nos of rows and how many nos of cols are there.

## Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.


In [13]:
arra.shape

(5,)

In [19]:
# multinested array
my_list1=[2,4,4,5]
my_list2=[2,4,5,3]
my_list3=[5,5,3,4]

arr=np.array([my_list1,my_list2,my_list3])


In [20]:
arr

array([[2, 4, 4, 5],
       [2, 4, 5, 3],
       [5, 5, 3, 4]])

In [21]:
arr.shape

(3, 4)

## Reshaping arrays
- Reshaping means changing the shape of an array.
- The shape of an array is the number of elements in each dimension.
- By reshaping we can add or remove dimensions or change number of elements in each dimension.


## Flattening the arrays
- Flattening array means converting a multidimensional array into a 1D array.

- We can use reshape(-1) to do this.

In [34]:
arr.reshape(-1)

array([2, 4, 4, 5, 2, 4, 5, 3, 5, 5, 3, 4])

In [24]:
arr.reshape(4,3)

array([[2, 4, 4],
       [5, 2, 4],
       [5, 3, 5],
       [5, 3, 4]])

In [29]:
arr.reshape(1,12)

array([[2, 4, 4, 5, 2, 4, 5, 3, 5, 5, 3, 4]])

In [30]:
lst=[1,2,3,4,5,6,7,8]
arrra=np.array(lst)
print(arrra)

[1 2 3 4 5 6 7 8]


In [31]:
arrra.reshape(2,2,-1)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:
arra.reshape(-1)

array([1, 2, 3, 4, 4])

# Indexing
- Access Array Elements
- Array indexing is the same as accessing an array element.

- You can access an array element by referring to its index number.

- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [36]:
lis=np.array([1,9,3,4,5,4,22])
lis

array([ 1,  9,  3,  4,  5,  4, 22])

In [37]:
lis[2]

3

In [39]:
# Get third and fourth elements from the following array and add them.
su=lis[2]+lis[3]
su

7

In [43]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10],[12,4,5,5,5]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [12,  4,  5,  5,  5]])

In [44]:
arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [12,  4,  5,  5,  5]])

In [48]:
arr[0:2,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [49]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [56]:
arr[1:,3:]

array([[ 9, 10],
       [ 5,  5]])

In [96]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# Inbuild function

In [60]:
# arange
arrr=np.arange(0,10,step=2)
arrr

array([0, 2, 4, 6, 8])

In [63]:
# linspace
lin=np.linspace(0,10,50)
lin

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [81]:
# ones
np.ones(4)

array([1., 1., 1., 1.])

In [83]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [84]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [85]:
# random distribution
# elements will b between 0,1
np.random.rand(2,3)

array([[0.73903032, 0.25754597, 0.69127224],
       [0.63661554, 0.27868993, 0.47774497]])

In [89]:
np.random.randn(2,3)

array([[ 0.19859191, -0.15140378,  0.01792349],
       [-0.78442772,  0.69341226, -0.12366215]])

In [90]:
np.random.randint(2,3,6)

array([2, 2, 2, 2, 2, 2])

In [91]:
np.random.randint(0,100,6)

array([56, 21, 44, 34, 60, 90])

In [95]:
np.random.random_sample((2,3))

array([[0.51225339, 0.60922932, 0.44789884],
       [0.0263307 , 0.97784411, 0.66454673]])

In [88]:
#copy function and broadcasting
lis=np.array([1,9,3,4,5,4,22])
lis

array([ 1,  9,  3,  4,  5,  4, 22])

In [65]:
lis[3:]=10

In [66]:
lis

array([ 1,  9,  3, 10, 10, 10, 10])

In [71]:
# referring lis to lis1
lis1=lis

In [72]:
lis1[3:]=50
lis1

array([ 1,  9,  3, 50, 50, 50, 50])

In [73]:
lis

array([ 1,  9,  3, 50, 50, 50, 50])

In [97]:
# sort
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [98]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [99]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [100]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [101]:
# split
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [102]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [103]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


(array([3, 5, 6], dtype=int64),)


- reference type:one operation done on one variable will affect the another
- value type:it can be integer type,this type of updation will not happen in case of reference type we are sharing the same memory

In [74]:
# to prevent the replication we have copy function
lis1=lis.copy()
lis

array([ 1,  9,  3, 50, 50, 50, 50])

In [75]:
lis1[3:]=100
lis1

array([  1,   9,   3, 100, 100, 100, 100])

In [76]:
lis

array([ 1,  9,  3, 50, 50, 50, 50])

In [77]:
# some  condition useful in EDA
lis<2

array([ True, False, False, False, False, False, False])

In [78]:
lis*2

array([  2,  18,   6, 100, 100, 100, 100])

In [80]:
lis[lis<5]

array([1, 3])